### PR TITLE
fix(zkevm-circuits): fix bug when calculating minimum rows of rlp_circuit

### PR DESCRIPTION
**Pull request by lightscale-luke**
* fix bug when calculating minimum rows of rlp_circuit

### CODE REVIEW

**Review by fakedev9999 — APPROVED** [review]
LGTM

**Comment by fakedev9999** [comment]
FYI, this is when all the disaster happened.
https://github.com/scroll-tech/zkevm-circuits/pull/243/files#diff-0eeeb8c86870bcb87104275bdb117f50540b69a2ae698123dadbcb48668e3680R1725-R1742

**Review by dongchangYoo — APPROVED** [review]
LGTM

**Review by chokobole — APPROVED** [review]
LGTM

**Pull request merged**
